# Generated by Django 3.2.6 on 2022-01-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.PositiveSmallIntegerField(choices=[(0, '介護保険'), (1, '障害者総合支援'), (2, '移動支援'), (3, '総合事業'), (4, '同行援護'), (5, '自費')], default=0, verbose_name='請求種別')),
                ('bill_title', models.CharField(default='', max_length=50, verbose_name='請求名称')),
                ('user_title', models.CharField(default='', max_length=50, verbose_name='利用者様用名称')),
                ('title', models.CharField(max_length=50, verbose_name='システム名称')),
                ('time', models.PositiveSmallIntegerField(verbose_name='標準総所要時間(分)')),
                ('min_time', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='最低時間(単一サービス時)')),
                ('mix_items', models.BooleanField(default=False, verbose_name='複数サービス混合')),
                ('name_main', models.CharField(blank=True, default='', max_length=50, verbose_name='名称メイン')),
                ('in_time_main', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='標準内訳時間メイン(分)')),
                ('min_time_main', models.PositiveSmallIntegerField(default=0, verbose_name='最低時間メイン(分)')),
                ('name_sub', models.CharField(blank=True, default='', max_length=50, verbose_name='名称サブ')),
                ('in_time_sub', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='標準内訳時間サブ(分)')),
                ('min_time_sub', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='最低時間サブ(分)')),
                ('destination', models.BooleanField(default=False, verbose_name='行先入力必須')),
                ('is_active', models.BooleanField(default=True, verbose_name='使用中')),
                ('biko', models.TextField(blank=True, default='', verbose_name='備考')),
            ],
        ),
    ]
