# Generated by Django 3.2.6 on 2021-10-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(0, '介護保険'), (1, '障害者総合支援'), (2, '移動支援'), (3, '総合事業'), (4, '同行援護'), (5, '自費')], default=0, verbose_name='請求種別'),
        ),
    ]
