# Generated by Django 3.2.6 on 2021-09-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='点数'),
        ),
    ]
