# Generated by Django 3.2.6 on 2022-01-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='points',
        ),
        migrations.AddField(
            model_name='service',
            name='bill_title',
            field=models.CharField(default='', max_length=50, verbose_name='請求名称'),
        ),
        migrations.AddField(
            model_name='service',
            name='destination',
            field=models.BooleanField(default=False, verbose_name='行先入力必須'),
        ),
        migrations.AddField(
            model_name='service',
            name='in_time',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='標準内訳時間メイン(分)'),
        ),
        migrations.AddField(
            model_name='service',
            name='in_time_sub',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='標準内訳時間サブ(分)'),
        ),
        migrations.AddField(
            model_name='service',
            name='min',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='最低時間メイン(分)'),
        ),
        migrations.AddField(
            model_name='service',
            name='min_sub',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='最低時間サブ(分)'),
        ),
        migrations.AddField(
            model_name='service',
            name='mix_items',
            field=models.BooleanField(default=False, verbose_name='身体・生活\u3000居宅・家事\u3000混合'),
        ),
        migrations.AddField(
            model_name='service',
            name='user_title',
            field=models.CharField(default='', max_length=50, verbose_name='利用者様用名称'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.PositiveSmallIntegerField(verbose_name='標準所要時間(分)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=50, verbose_name='システム名称'),
        ),
    ]
