# Generated by Django 3.2.6 on 2021-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='kind',
            field=models.PositiveSmallIntegerField(choices=[(0, '介護保険'), (1, '障害福祉'), (2, '自費')], default=0, verbose_name='請求種別'),
        ),
    ]
