# Generated by Django 3.2.6 on 2021-09-05 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='points',
        ),
    ]
