# Generated by Django 3.2.6 on 2022-01-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20220123_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='min',
            new_name='min_time',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='min_sub',
            new_name='min_time_sub',
        ),
    ]
