# Generated by Django 3.2.6 on 2022-01-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20220123_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='min_time_main',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='最低時間メイン(分)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_main',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='名称メイン'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_sub',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='名称サブ'),
        ),
        migrations.AlterField(
            model_name='service',
            name='in_time',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='標準内訳時間メイン(分)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_time',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='最低時間(単一サービス時)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='mix_items',
            field=models.BooleanField(default=False, verbose_name='複数サービス混合'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.PositiveSmallIntegerField(verbose_name='標準総所要時間(分)'),
        ),
    ]
