# Generated by Django 3.2.6 on 2021-09-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='点数'),
        ),
    ]
