# Generated by Django 3.2.6 on 2022-01-24 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20220124_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='in_time',
            new_name='in_time_main',
        ),
    ]
