# Generated by Django 3.2.6 on 2021-09-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='biko',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
    ]
