# Generated by Django 3.2.6 on 2021-08-13 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='姓')),
                ('first_name', models.CharField(max_length=30, verbose_name='名')),
                ('last_kana', models.CharField(max_length=30, verbose_name='せい')),
                ('first_kana', models.CharField(max_length=30, verbose_name='めい')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性別')),
                ('birthday', models.DateField(blank=True, verbose_name='生年月日')),
                ('user_no', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='利用者番号')),
                ('postcode', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('adr_ken', models.CharField(max_length=4, verbose_name='県')),
                ('adr_siku', models.CharField(max_length=30, verbose_name='市区町村')),
                ('adr_tyou', models.CharField(max_length=30, verbose_name='町名・番地')),
                ('adr_bld', models.CharField(blank=True, default='', max_length=40, verbose_name='ビル・マンション名')),
                ('tel', models.CharField(blank=True, default='', max_length=15, verbose_name='電話番号')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='携帯')),
                ('startdate', models.DateField(blank=True, verbose_name='契約日')),
                ('biko', models.TextField(blank=True, default='', verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='利用中')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '曜日指定'), (1, '日指定')], default=0, verbose_name='')),
                ('weektype', models.PositiveSmallIntegerField(choices=[(0, '毎週'), (1, '隔週1-3-5'), (2, '隔週2-4'), (3, '第1'), (4, '第2'), (5, '第3'), (6, '第4')], default=0, verbose_name='')),
                ('sun', models.BooleanField(default=False, verbose_name='日')),
                ('mon', models.BooleanField(default=False, verbose_name='月')),
                ('tue', models.BooleanField(default=False, verbose_name='火')),
                ('wed', models.BooleanField(default=False, verbose_name='水')),
                ('thu', models.BooleanField(default=False, verbose_name='木')),
                ('fri', models.BooleanField(default=False, verbose_name='金')),
                ('sat', models.BooleanField(default=False, verbose_name='土')),
                ('daytype', models.PositiveSmallIntegerField(choices=[(0, '毎日'), (1, '奇数日'), (2, '偶数日'), (3, '日付指定')], default=0, verbose_name='')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='日')),
                ('biko', models.TextField(blank=True, default='', verbose_name='備考')),
                ('careuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careusers.careuser')),
            ],
        ),
    ]
