# Generated by Django 3.2.6 on 2021-10-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careuser',
            name='startdate',
            field=models.DateField(blank=True, null=True, verbose_name='契約日'),
        ),
    ]
