# Generated by Django 3.2.6 on 2021-10-20 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultschedule',
            name='daytype',
            field=models.PositiveSmallIntegerField(choices=[(0, '毎日'), (1, '奇数日'), (2, '偶数日'), (3, '日付指定')], default=0, validators=[django.core.validators.RegexValidator(regex='0[1-9]|[12][0-9]|3[01]')], verbose_name='日指定'),
        ),
        migrations.AlterField(
            model_name='defaultschedule',
            name='start_h',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='[01][0-9]|2[0-3]')], verbose_name='開始時'),
        ),
        migrations.AlterField(
            model_name='defaultschedule',
            name='start_m',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='[0-5][0-9]')], verbose_name='開始分'),
        ),
    ]
