# Generated by Django 3.2.6 on 2021-08-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(0, '曜日指定'), (1, '日指定')], default=0, verbose_name='')),
                ('weektype', models.PositiveSmallIntegerField(choices=[(0, '毎週'), (1, '隔週1-3-5'), (2, '隔週2-4'), (3, '第1'), (4, '第2'), (5, '第3'), (6, '第4')], default=0, verbose_name='')),
                ('sun', models.BooleanField(default=False, verbose_name='日')),
                ('mon', models.BooleanField(default=False, verbose_name='月')),
                ('tue', models.BooleanField(default=False, verbose_name='火')),
                ('wed', models.BooleanField(default=False, verbose_name='水')),
                ('thu', models.BooleanField(default=False, verbose_name='木')),
                ('fri', models.BooleanField(default=False, verbose_name='金')),
                ('sat', models.BooleanField(default=False, verbose_name='土')),
                ('daytype', models.PositiveSmallIntegerField(choices=[(0, '毎日'), (1, '奇数日'), (2, '偶数日'), (3, '日付指定')], default=0, verbose_name='')),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='日')),
                ('biko', models.TextField(blank=True, default='', verbose_name='備考')),
                ('careuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careusers.careuser')),
            ],
        ),
    ]
