# Generated by Django 3.2.6 on 2021-08-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Careuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='姓')),
                ('first_name', models.CharField(max_length=30, verbose_name='名')),
                ('last_kana', models.CharField(max_length=30, verbose_name='せい')),
                ('first_kana', models.CharField(max_length=30, verbose_name='めい')),
                ('birthday', models.DateField(blank=True, verbose_name='生年月日')),
                ('user_no', models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='利用者番号')),
                ('postcode', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('adr_ken', models.CharField(max_length=4, verbose_name='県')),
                ('adr_siku', models.CharField(max_length=30, verbose_name='市区町村')),
                ('adr_tyou', models.CharField(max_length=30, verbose_name='町名・番地')),
                ('adr_bld', models.CharField(blank=True, default='', max_length=40, verbose_name='ビル・マンション名')),
                ('tel', models.CharField(blank=True, default='', max_length=15, verbose_name='電話番号')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='携帯')),
                ('startdate', models.DateField(blank=True, verbose_name='契約日')),
                ('biko', models.TextField(blank=True, default='', verbose_name='備考')),
                ('is_active', models.BooleanField(default=True, verbose_name='利用中')),
            ],
        ),
        migrations.DeleteModel(
            name='careusers',
        ),
    ]
