# Generated by Django 3.2.6 on 2021-09-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careuser',
            name='short_name',
        ),
    ]
