# Generated by Django 3.2.6 on 2021-08-14 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careusers', '0002_alter_careuser_adr_ken'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultschedule',
            name='staffs',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defaultschedule',
            name='start_h',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='開始時'),
        ),
        migrations.AddField(
            model_name='defaultschedule',
            name='start_m',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='開始分'),
        ),
    ]
