# Generated by Django 3.2.6 on 2021-08-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0002_defaultshift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultShift',
            new_name='DefaultSchedule',
        ),
    ]
