# Generated by Django 3.2.6 on 2022-03-21 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0002_defaultschedule_add_stop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultschedule',
            name='start_h',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='開始時'),
        ),
        migrations.AlterField(
            model_name='defaultschedule',
            name='start_m',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='開始分'),
        ),
    ]
