# Generated by Django 3.2.6 on 2021-09-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0002_remove_careuser_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='careuser',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='短縮名'),
        ),
    ]
