# Generated by Django 3.2.6 on 2021-10-20 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0002_auto_20211020_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultschedule',
            name='day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='0[1-9]|[12][0-9]|3[01]')], verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='defaultschedule',
            name='daytype',
            field=models.PositiveSmallIntegerField(choices=[(0, '毎日'), (1, '奇数日'), (2, '偶数日'), (3, '日付指定')], default=0, verbose_name='日指定'),
        ),
    ]
