# Generated by Django 3.2.6 on 2021-08-18 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careusers', '0003_auto_20210814_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultschedule',
            name='staffs',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ'),
        ),
    ]
