# Generated by Django 3.2.6 on 2021-08-19 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0004_alter_defaultschedule_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultschedule',
            name='careuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careusers.careuser', verbose_name='利用者名'),
        ),
        migrations.AlterField(
            model_name='defaultschedule',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, '週ベース'), (1, '日ベース')], default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='defaultschedule',
            name='weektype',
            field=models.PositiveSmallIntegerField(choices=[(0, '毎週'), (1, '隔週1-3-5'), (2, '隔週2-4'), (3, '第1週'), (4, '第2週'), (5, '第3週'), (6, '第4週')], default=0, verbose_name=''),
        ),
    ]
