# Generated by Django 3.2.6 on 2021-10-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0005_auto_20211028_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultschedule',
            name='weektype',
            field=models.PositiveSmallIntegerField(choices=[(0, '毎週'), (1, '隔週1-3-5'), (2, '隔週2-4'), (3, '第1'), (4, '第2'), (5, '第3'), (6, '第4'), (7, '第5')], default=0, verbose_name='週指定'),
        ),
    ]
