# Generated by Django 3.2.6 on 2021-08-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0006_defaultschedule_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultschedule',
            name='daytype',
            field=models.PositiveSmallIntegerField(choices=[(0, '毎日'), (1, '奇数日'), (2, '偶数日'), (3, '日付指定')], default=0, verbose_name='日指定'),
        ),
        migrations.AlterField(
            model_name='defaultschedule',
            name='weektype',
            field=models.PositiveSmallIntegerField(choices=[(0, '毎週'), (1, '隔週1-3-5'), (2, '隔週2-4'), (3, '第1'), (4, '第2'), (5, '第3'), (6, '第4')], default=0, verbose_name='週指定'),
        ),
    ]
