# Generated by Django 3.2.6 on 2021-08-26 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('careusers', '0007_auto_20210826_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultschedule',
            name='peoples',
            field=models.PositiveSmallIntegerField(choices=[(1, '1名'), (2, '2名'), (3, '3名'), (4, '4名')], default=1, verbose_name='必要人数'),
        ),
        migrations.AlterField(
            model_name='defaultschedule',
            name='staffs',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='サービス可能スタッフ'),
        ),
    ]
