# Generated by Django 3.2.6 on 2021-12-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0007_defaultschedule_no_set_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='careuser',
            name='report_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='サービス実施記録送信先メールアドレス'),
        ),
        migrations.AddField(
            model_name='careuser',
            name='report_send',
            field=models.BooleanField(default=False, verbose_name='サービス実施記録メール送信'),
        ),
    ]
