# Generated by Django 3.2.6 on 2022-01-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careusers', '0008_auto_20211211_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='careuser',
            name='no_active_date',
            field=models.DateField(blank=True, null=True, verbose_name='利用終了日時'),
        ),
    ]
