# Generated by Django 3.2.6 on 2021-08-11 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sei', models.CharField(max_length=10, verbose_name='姓')),
                ('mei', models.CharField(max_length=10, verbose_name='名')),
                ('kana_sei', models.CharField(max_length=10, verbose_name='せい')),
                ('kana_mei', models.CharField(max_length=10, verbose_name='めい')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('staff_no', models.PositiveSmallIntegerField(blank=True, verbose_name='社員番号')),
                ('postcode', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('adr_ken', models.CharField(max_length=4, verbose_name='県')),
                ('adr_siku', models.CharField(max_length=30, verbose_name='市区町村')),
                ('adr_tyou', models.CharField(max_length=30, verbose_name='町名・番地')),
                ('adr_bld', models.CharField(blank=True, default='', max_length=40, verbose_name='ビル・マンション名')),
                ('tel', models.CharField(blank=True, default='', max_length=15, verbose_name='電話番号')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='携帯')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('shaho', models.BooleanField(default=False, verbose_name='社会保険加入')),
                ('join', models.DateField(verbose_name='入社日')),
                ('biko', models.TextField(blank=True, default='', verbose_name='備考')),
                ('kanri', models.BooleanField(default=False, verbose_name='管理者')),
                ('jimu', models.BooleanField(default=False, verbose_name='事務員')),
                ('reader', models.BooleanField(default=False, verbose_name='グループリーダー')),
                ('caremane', models.BooleanField(default=False, verbose_name='ケアマネージャー')),
                ('servkan', models.BooleanField(default=False, verbose_name='サービス提供責任者')),
                ('kaigo', models.BooleanField(default=False, verbose_name='介護職員')),
                ('yougu', models.BooleanField(default=False, verbose_name='福祉用具専門相談員')),
                ('kango', models.BooleanField(default=False, verbose_name='看護職員')),
                ('kinou', models.BooleanField(default=False, verbose_name='機能訓練指導員')),
                ('seikatu', models.BooleanField(default=False, verbose_name='生活相談員')),
                ('ishi', models.BooleanField(default=False, verbose_name='医師')),
                ('riha', models.BooleanField(default=False, verbose_name='リハ職員')),
                ('ope', models.BooleanField(default=False, verbose_name='オペレーター')),
                ('ryouyou', models.BooleanField(default=False, verbose_name='療養管理指導員')),
                ('jihakan', models.BooleanField(default=False, verbose_name='児童発達支援管理責任者')),
                ('sidou', models.BooleanField(default=False, verbose_name='指導員')),
                ('hoiku', models.BooleanField(default=False, verbose_name='保育士')),
                ('jisou', models.BooleanField(default=False, verbose_name='児童指導員')),
                ('driver', models.BooleanField(default=False, verbose_name='ドライバー')),
                ('eiyou', models.BooleanField(default=False, verbose_name='栄養士')),
                ('tyouri', models.BooleanField(default=False, verbose_name='調理師')),
                ('gengo', models.BooleanField(default=False, verbose_name='言語機能訓練指導員')),
                ('tyounou', models.BooleanField(default=False, verbose_name='聴能訓練指導員')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
