# Generated by Django 3.2.6 on 2021-08-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adr_ken',
            field=models.CharField(max_length=4, verbose_name='都道府県'),
        ),
    ]
