# Generated by Django 3.2.6 on 2022-03-14 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '固定'), (2, '歩合')], default=2, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='給与体系'),
        ),
    ]
