# Generated by Django 3.2.6 on 2021-10-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jitumu',
            field=models.BooleanField(default=False, verbose_name='実務者研修'),
        ),
        migrations.AddField(
            model_name='user',
            name='shonin',
            field=models.BooleanField(default=False, verbose_name='初任者研修'),
        ),
    ]
