# Generated by Django 3.2.6 on 2021-12-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doukou',
            field=models.BooleanField(default=False, verbose_name='同行援護従業者養成研修'),
        ),
    ]
