# Generated by Django 3.2.6 on 2021-10-14 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20211014_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='helper2',
            field=models.BooleanField(default=False, verbose_name='ホームヘルパー2級(旧)'),
        ),
        migrations.AddField(
            model_name='user',
            name='kisoken',
            field=models.BooleanField(default=False, verbose_name='介護職員基礎研修(旧)'),
        ),
    ]
