# Generated by Django 3.2.6 on 2022-04-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_user_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_bike',
            field=models.BooleanField(default=False, verbose_name='バイク代支給'),
        ),
    ]
