# Generated by Django 3.2.6 on 2021-08-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_alter_user_adr_ken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_name',
            field=models.CharField(default='', max_length=30, verbose_name='短縮名'),
        ),
    ]
