# Generated by Django 3.2.6 on 2022-01-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_user_doukou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jimu',
            field=models.BooleanField(default=False, verbose_name='事務員(利用停止済みを表示に必須)'),
        ),
    ]
