# Generated by Django 3.2.6 on 2021-09-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_user_servsou'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kaifuku',
            field=models.BooleanField(default=False, verbose_name='介護福祉士'),
        ),
        migrations.AddField(
            model_name='user',
            name='sousien',
            field=models.BooleanField(default=False, verbose_name='相談支援専門員'),
        ),
    ]
