# Generated by Django 3.2.6 on 2021-10-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_auto_20211014_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kaigo',
            field=models.BooleanField(default=False, verbose_name='介護職員(一覧表示に必須)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kisoken',
            field=models.BooleanField(default=False, verbose_name='基礎研修(旧)'),
        ),
    ]
