# Generated by Django 3.2.6 on 2021-08-30 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careusers', '__first__'),
        ('services', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='日時')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('peoples', models.PositiveSmallIntegerField(choices=[(1, '1名'), (2, '2名'), (3, '3名'), (4, '4名')], default=1, verbose_name='必要人数')),
                ('biko', models.TextField(blank=True, default='', verbose_name='備考')),
                ('kaigo_point', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='介護点数')),
                ('shogai_point', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='障害点数')),
                ('def_sche_id', models.PositiveIntegerField(default=0, verbose_name='標準スケジュールからの登録PK')),
                ('check_flg', models.BooleanField(default=False, verbose_name='要チェックフラグ')),
                ('comfirm_flg', models.BooleanField(default=False, verbose_name='確定済みサイン')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('careuser', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='careusers.careuser', verbose_name='利用者名')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='登録スタッフ')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='services.service', verbose_name='利用サービス')),
                ('staff1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staffs1', to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ１')),
                ('staff2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staffs2', to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ２')),
                ('staff3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staffs3', to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ３')),
                ('staff4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staffs4', to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ４')),
                ('tr_staff1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tr_staffs1', to=settings.AUTH_USER_MODEL, verbose_name='研修スタッフ１')),
                ('tr_staff2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tr_staffs2', to=settings.AUTH_USER_MODEL, verbose_name='研修スタッフ２')),
                ('tr_staff3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tr_staffs3', to=settings.AUTH_USER_MODEL, verbose_name='研修スタッフ３')),
                ('tr_staff4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tr_staffs4', to=settings.AUTH_USER_MODEL, verbose_name='研修スタッフ４')),
            ],
        ),
    ]
