# Generated by Django 3.2.6 on 2021-08-20 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careusers', '0006_defaultschedule_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_alter_service_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='日時')),
                ('biko', models.TextField(blank=True, default='', verbose_name='備考')),
                ('kaigo_point', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='介護点数')),
                ('shogai_point', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='障害点数')),
                ('careuser', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='careusers.careuser', verbose_name='利用者名')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='services.service', verbose_name='利用サービス')),
                ('staffs1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ１')),
            ],
        ),
    ]
