# Generated by Django 3.2.6 on 2021-11-12 03:57

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='defecation_t',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='排便回数'),
        ),
        migrations.AlterField(
            model_name='report',
            name='eating',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '完食'), (2, '一部')], default=0, verbose_name='摂食介助'),
        ),
        migrations.AlterField(
            model_name='report',
            name='face_color',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '良'), (2, '不良')], default=0, verbose_name='顔色'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hakkan',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '有'), (2, '無')], default=0, verbose_name='発汗'),
        ),
        migrations.AlterField(
            model_name='report',
            name='urination_a',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='排尿量'),
        ),
        migrations.AlterField(
            model_name='report',
            name='urination_t',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='排尿回数'),
        ),
    ]
