# Generated by Django 3.2.6 on 2021-08-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='def_sche_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='from_default',
            field=models.BooleanField(default=False, verbose_name='DefaultScheduleからの登録'),
        ),
    ]
