# Generated by Django 3.2.6 on 2021-09-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='service_in_date',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='service_out_date',
        ),
    ]
