# Generated by Django 3.2.6 on 2021-09-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20210925_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='service_in_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='サービス開始日時'),
        ),
        migrations.AddField(
            model_name='report',
            name='service_out_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='サービス終了日時'),
        ),
    ]
