# Generated by Django 3.2.6 on 2021-11-24 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0002_auto_20211112_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowUserEnddate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(verbose_name='表示最終日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
        ),
    ]
