# Generated by Django 3.2.6 on 2021-08-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20210830_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='from_default',
        ),
        migrations.AddField(
            model_name='schedule',
            name='def_sche_id',
            field=models.PositiveIntegerField(default=0, verbose_name='標準スケジュールからの登録PK'),
        ),
    ]
