# Generated by Django 3.2.6 on 2021-10-14 02:17

from django.db import migrations, models
import schedules.models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20210925_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='biko',
            field=models.TextField(verbose_name='特記・連絡事項'),
        ),
        migrations.AlterField(
            model_name='report',
            name='service_in_date',
            field=models.DateTimeField(null=True, validators=[schedules.models.check_time], verbose_name='サービス開始日時'),
        ),
        migrations.AlterField(
            model_name='report',
            name='service_out_date',
            field=models.DateTimeField(null=True, verbose_name='サービス終了日時'),
        ),
    ]
