# Generated by Django 3.2.6 on 2021-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20210830_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='check_flg',
        ),
        migrations.AddField(
            model_name='schedule',
            name='careuser_check_level',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='利用者チェックフラグ'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='staff_check_level',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='利用者チェックフラグ'),
        ),
    ]
