# Generated by Django 3.2.6 on 2021-12-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_showuserenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='入力ロック'),
        ),
        migrations.AlterField(
            model_name='report',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='預り金'),
        ),
        migrations.AlterField(
            model_name='report',
            name='payment',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='買物'),
        ),
        migrations.AlterField(
            model_name='report',
            name='washing',
            field=models.BooleanField(default=False, verbose_name='洗濯'),
        ),
    ]
