# Generated by Django 3.2.6 on 2021-08-20 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0003_auto_20210820_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='staffs1',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staffs1', to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ１'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='staffs2',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staffs2', to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ２'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='staffs3',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staffs3', to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ３'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='staffs4',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staffs4', to=settings.AUTH_USER_MODEL, verbose_name='担当スタッフ４'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tr_staff1',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tr_staffs1', to=settings.AUTH_USER_MODEL, verbose_name='研修スタッフ１'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tr_staff2',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tr_staffs2', to=settings.AUTH_USER_MODEL, verbose_name='研修スタッフ２'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tr_staff3',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tr_staffs3', to=settings.AUTH_USER_MODEL, verbose_name='研修スタッフ３'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tr_staff4',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tr_staffs4', to=settings.AUTH_USER_MODEL, verbose_name='研修スタッフ４'),
        ),
    ]
