# Generated by Django 3.2.6 on 2022-01-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_rename_mix_reverce_report_mix_reverse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='drink_a',
        ),
        migrations.RemoveField(
            model_name='report',
            name='eat_a',
        ),
    ]
