# Generated by Django 3.2.6 on 2021-12-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20211211_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='入力ロック（入力後は登録ヘルパーさんは改変不可とします。）'),
        ),
    ]
