# Generated by Django 3.2.6 on 2022-01-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20220127_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='drink_a',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='水分補給'),
        ),
        migrations.AddField(
            model_name='report',
            name='eat_a',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='食事量'),
        ),
    ]
