# Generated by Django 3.2.6 on 2021-09-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20210906_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='service_titile',
            new_name='service_title',
        ),
    ]
