# Generated by Django 3.2.6 on 2021-08-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20210820_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='from_default',
            field=models.BooleanField(default=False, verbose_name='DefaultScheduleからの登録'),
        ),
    ]
