# Generated by Django 3.2.6 on 2022-01-27 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20220127_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bath',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '全身浴'), (2, '全身シャワー浴'), (3, '部分浴：手'), (4, '部分浴：足'), (5, '部分浴：手足')], default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='入浴'),
        ),
        migrations.AlterField(
            model_name='report',
            name='bedbath',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '全身'), (2, '部分')], default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='清拭'),
        ),
        migrations.AlterField(
            model_name='report',
            name='blood_pre_h',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)], verbose_name='血圧High'),
        ),
        migrations.AlterField(
            model_name='report',
            name='blood_pre_l',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='血圧Low'),
        ),
        migrations.AlterField(
            model_name='report',
            name='body_temp',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(45)], verbose_name='体温'),
        ),
        migrations.AlterField(
            model_name='report',
            name='defecation_t',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='排便回数'),
        ),
        migrations.AlterField(
            model_name='report',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='預り金'),
        ),
        migrations.AlterField(
            model_name='report',
            name='drink_a',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='水分補給'),
        ),
        migrations.AlterField(
            model_name='report',
            name='eat_a',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='食事量'),
        ),
        migrations.AlterField(
            model_name='report',
            name='eating',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '完食'), (2, '一部')], default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='摂食介助'),
        ),
        migrations.AlterField(
            model_name='report',
            name='error_code',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='エラーコード'),
        ),
        migrations.AlterField(
            model_name='report',
            name='face_color',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '良'), (2, '不良')], default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='顔色'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hakkan',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '有'), (2, '無')], default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='発汗'),
        ),
        migrations.AlterField(
            model_name='report',
            name='in_time_main',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(4320)], verbose_name='内訳時間メイン(分)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='in_time_sub',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(4320)], verbose_name='内訳時間サブ(分)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='payment',
            field=models.PositiveIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(1000000)], verbose_name='買物'),
        ),
        migrations.AlterField(
            model_name='report',
            name='urination_a',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='排尿量'),
        ),
        migrations.AlterField(
            model_name='report',
            name='urination_t',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(99)], verbose_name='排尿回数'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='biko',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='peoples',
            field=models.PositiveSmallIntegerField(choices=[(1, '1名'), (2, '2名'), (3, '3名'), (4, '4名')], default=1, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='必要人数'),
        ),
    ]
