# Generated by Django 3.2.6 on 2022-01-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20211223_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='locked',
        ),
        migrations.AddField(
            model_name='report',
            name='careuser_comfirmed',
            field=models.BooleanField(default=False, verbose_name='利用者様確認済み（確認後は登録ヘルパーさんは修正不可となります。）'),
        ),
    ]
