# Generated by Django 3.2.6 on 2021-09-05 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_points'),
        ('schedules', '0006_rename_service_titile_schedule_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='利用サービス'),
            preserve_default=False,
        ),
    ]
