# Generated by Django 3.2.6 on 2021-08-20 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_schedule_from_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='staffs1',
            new_name='staff1',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='staffs2',
            new_name='staff2',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='staffs3',
            new_name='staff3',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='staffs4',
            new_name='staff4',
        ),
    ]
