# Generated by Django 3.2.6 on 2022-01-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20220115_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='行先'),
        ),
        migrations.AlterField(
            model_name='report',
            name='biko',
            field=models.TextField(max_length=200, verbose_name='特記・連絡事項'),
        ),
    ]
