# Generated by Django 3.2.6 on 2021-09-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20210906_0722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='service',
        ),
    ]
