# Generated by Django 3.2.6 on 2021-08-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20210821_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='peoples',
            field=models.PositiveSmallIntegerField(choices=[(1, '1名'), (2, '2名'), (3, '3名'), (4, '4名')], default=1, verbose_name='必要人数'),
        ),
    ]
