# Generated by Django 3.2.6 on 2022-01-28 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20220128_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Diapers',
            new_name='diapers',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='Pads',
            new_name='pads',
        ),
    ]
