# Generated by Django 3.2.6 on 2022-01-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20220122_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='communicate',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='予定変更理由等'),
        ),
        migrations.AddField(
            model_name='report',
            name='error_code',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='エラーコード'),
        ),
        migrations.AddField(
            model_name='report',
            name='in_time_main',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='内訳時間メイン(分)'),
        ),
        migrations.AddField(
            model_name='report',
            name='in_time_sub',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='内訳時間サブ(分)'),
        ),
        migrations.AddField(
            model_name='report',
            name='mix_reverce',
            field=models.BooleanField(default=False, verbose_name='混合サービス順序'),
        ),
        migrations.AlterField(
            model_name='report',
            name='biko',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='特記・連絡事項'),
        ),
        migrations.AlterField(
            model_name='report',
            name='service_in_date',
            field=models.DateTimeField(null=True, verbose_name='サービス開始日時'),
        ),
    ]
