# Generated by Django 3.2.6 on 2021-08-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_schedule_peoples'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='check_flg',
            field=models.BooleanField(default=False, verbose_name='要チェックフラグ'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='comfirm_flg',
            field=models.BooleanField(default=False, verbose_name='確定済みサイン'),
        ),
    ]
