# Generated by Django 3.2.6 on 2022-01-28 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20220129_0259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='Receive_mad',
            new_name='receive_mad',
        ),
    ]
