# Generated by Django 3.2.6 on 2021-09-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_points'),
        ('schedules', '0009_remove_schedule_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='services.service', verbose_name='利用サービス'),
        ),
    ]
