# Generated by Django 3.2.6 on 2022-01-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_rename_receive_mad_report_receive_mad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='careuser_comfirmed',
            new_name='careuser_confirmed',
        ),
    ]
