# Generated by Django 3.2.6 on 2021-08-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_auto_20210826_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='終了日時'),
        ),
    ]
