# Generated by Django 3.2.6 on 2021-09-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_schedule_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='idou_point',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='jihi_point',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='kaigo_point',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='service_title',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='shogai_point',
        ),
    ]
