# Generated by Django 3.2.6 on 2021-09-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_biko'),
        ('schedules', '0011_auto_20210906_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='services.service', verbose_name='利用サービス'),
        ),
    ]
