# Generated by Django 3.2.6 on 2022-01-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_rename_careuser_comfirmed_report_careuser_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email_sent_date',
            field=models.DateTimeField(null=True, verbose_name='実績記録e-mail送信日時'),
        ),
    ]
