# Generated by Django 3.2.6 on 2021-08-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_auto_20210827_2013'),
        ('schedules', '0012_auto_20210827_2015'),
    ]

    operations = [
    ]
