# Generated by Django 3.2.6 on 2021-09-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_alter_schedule_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='service_indate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予定終了日時'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='service_outdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予定終了日時'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='予定終了日時'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(verbose_name='予定日時'),
        ),
    ]
