# Generated by Django 3.2.6 on 2021-09-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_auto_20210910_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='service_indate',
            new_name='service_in_date',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='service_outdate',
            new_name='service_out_date',
        ),
    ]
