# Generated by Django 3.2.6 on 2021-09-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='Diapers',
            field=models.BooleanField(default=False, verbose_name='おむつ交換'),
        ),
        migrations.AddField(
            model_name='report',
            name='Pads',
            field=models.BooleanField(default=False, verbose_name='パッド交換'),
        ),
        migrations.AddField(
            model_name='report',
            name='Receive_mad',
            field=models.BooleanField(default=False, verbose_name='薬の受取り'),
        ),
        migrations.AddField(
            model_name='report',
            name='bath',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '全身浴'), (2, '全身シャワー浴'), (3, '部分浴：手'), (4, '部分浴：足'), (5, '部分浴：手足')], default=0, verbose_name='入浴'),
        ),
        migrations.AddField(
            model_name='report',
            name='bed_change',
            field=models.BooleanField(default=False, verbose_name='シーツ・カバー交換'),
        ),
        migrations.AddField(
            model_name='report',
            name='bed_dry',
            field=models.BooleanField(default=False, verbose_name='布団干し'),
        ),
        migrations.AddField(
            model_name='report',
            name='bed_making',
            field=models.BooleanField(default=False, verbose_name='ベッドメイク'),
        ),
        migrations.AddField(
            model_name='report',
            name='bedbath',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '全身'), (2, '部分')], default=0, verbose_name='清拭'),
        ),
        migrations.AddField(
            model_name='report',
            name='biko',
            field=models.TextField(blank=True, default='', verbose_name='特記・連絡事項'),
        ),
        migrations.AddField(
            model_name='report',
            name='change_cloth',
            field=models.BooleanField(default=False, verbose_name='更衣介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='change_pos',
            field=models.BooleanField(default=False, verbose_name='体位変換'),
        ),
        migrations.AddField(
            model_name='report',
            name='cl_bath',
            field=models.BooleanField(default=False, verbose_name='浴室'),
        ),
        migrations.AddField(
            model_name='report',
            name='cl_bedroom',
            field=models.BooleanField(default=False, verbose_name='寝室'),
        ),
        migrations.AddField(
            model_name='report',
            name='cl_front',
            field=models.BooleanField(default=False, verbose_name='玄関'),
        ),
        migrations.AddField(
            model_name='report',
            name='cl_hall',
            field=models.BooleanField(default=False, verbose_name='廊下'),
        ),
        migrations.AddField(
            model_name='report',
            name='cl_kitchen',
            field=models.BooleanField(default=False, verbose_name='台所'),
        ),
        migrations.AddField(
            model_name='report',
            name='cl_p_toilet',
            field=models.BooleanField(default=False, verbose_name='Pトイレ'),
        ),
        migrations.AddField(
            model_name='report',
            name='cl_room',
            field=models.BooleanField(default=False, verbose_name='居室'),
        ),
        migrations.AddField(
            model_name='report',
            name='cl_table',
            field=models.BooleanField(default=False, verbose_name='卓上'),
        ),
        migrations.AddField(
            model_name='report',
            name='cl_toilet',
            field=models.BooleanField(default=False, verbose_name='トイレ'),
        ),
        migrations.AddField(
            model_name='report',
            name='cl_trush',
            field=models.BooleanField(default=False, verbose_name='ゴミ出し'),
        ),
        migrations.AddField(
            model_name='report',
            name='cloth_repair',
            field=models.BooleanField(default=False, verbose_name='被服の補修'),
        ),
        migrations.AddField(
            model_name='report',
            name='cloth_sort',
            field=models.BooleanField(default=False, verbose_name='衣類の整理'),
        ),
        migrations.AddField(
            model_name='report',
            name='cook_lower',
            field=models.BooleanField(default=False, verbose_name='下拵え'),
        ),
        migrations.AddField(
            model_name='report',
            name='cook_menu',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='献立'),
        ),
        migrations.AddField(
            model_name='report',
            name='cook_prepare',
            field=models.BooleanField(default=False, verbose_name='配・下膳'),
        ),
        migrations.AddField(
            model_name='report',
            name='cooking',
            field=models.BooleanField(default=False, verbose_name='調理'),
        ),
        migrations.AddField(
            model_name='report',
            name='daily_shop',
            field=models.BooleanField(default=False, verbose_name='日常品等買物'),
        ),
        migrations.AddField(
            model_name='report',
            name='defecation_s',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='排便状態'),
        ),
        migrations.AddField(
            model_name='report',
            name='defecation_t',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='排便回数'),
        ),
        migrations.AddField(
            model_name='report',
            name='deposit',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='預り金'),
        ),
        migrations.AddField(
            model_name='report',
            name='dring_a',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='水分補給(cc)'),
        ),
        migrations.AddField(
            model_name='report',
            name='eat_a',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='食事量(%)'),
        ),
        migrations.AddField(
            model_name='report',
            name='eating',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '全'), (2, '一部')], default=0, verbose_name='摂食介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='emergency',
            field=models.BooleanField(default=False, verbose_name='緊急'),
        ),
        migrations.AddField(
            model_name='report',
            name='eye_drops',
            field=models.BooleanField(default=False, verbose_name='点眼'),
        ),
        migrations.AddField(
            model_name='report',
            name='first',
            field=models.BooleanField(default=False, verbose_name='初回'),
        ),
        migrations.AddField(
            model_name='report',
            name='goingtobed',
            field=models.BooleanField(default=False, verbose_name='就寝介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='gotohospital',
            field=models.BooleanField(default=False, verbose_name='通院介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='gotoshopping',
            field=models.BooleanField(default=False, verbose_name='買物介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='in_hospital',
            field=models.BooleanField(default=False, verbose_name='院内介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='inbu',
            field=models.BooleanField(default=False, verbose_name='陰部清潔'),
        ),
        migrations.AddField(
            model_name='report',
            name='jir_call_out',
            field=models.BooleanField(default=False, verbose_name='声かけと見守り'),
        ),
        migrations.AddField(
            model_name='report',
            name='jir_memory',
            field=models.BooleanField(default=False, verbose_name='記憶への働きかけ'),
        ),
        migrations.AddField(
            model_name='report',
            name='jir_motivate',
            field=models.BooleanField(default=False, verbose_name='意欲関心の引き出し'),
        ),
        migrations.AddField(
            model_name='report',
            name='jir_shopping',
            field=models.BooleanField(default=False, verbose_name='買物援助'),
        ),
        migrations.AddField(
            model_name='report',
            name='jir_together',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='共に行う(内容)'),
        ),
        migrations.AddField(
            model_name='report',
            name='linen',
            field=models.BooleanField(default=False, verbose_name='リネン等交換処理'),
        ),
        migrations.AddField(
            model_name='report',
            name='makeup_beard',
            field=models.BooleanField(default=False, verbose_name='整容（髭）'),
        ),
        migrations.AddField(
            model_name='report',
            name='makeup_ear',
            field=models.BooleanField(default=False, verbose_name='整容（耳）'),
        ),
        migrations.AddField(
            model_name='report',
            name='makeup_fase',
            field=models.BooleanField(default=False, verbose_name='整容（化粧）'),
        ),
        migrations.AddField(
            model_name='report',
            name='makeup_hair',
            field=models.BooleanField(default=False, verbose_name='整容（髪）'),
        ),
        migrations.AddField(
            model_name='report',
            name='makeup_nail',
            field=models.BooleanField(default=False, verbose_name='整容（爪）'),
        ),
        migrations.AddField(
            model_name='report',
            name='medicine',
            field=models.BooleanField(default=False, verbose_name='服薬介助・確認'),
        ),
        migrations.AddField(
            model_name='report',
            name='medicine_app',
            field=models.BooleanField(default=False, verbose_name='薬の塗布'),
        ),
        migrations.AddField(
            model_name='report',
            name='move',
            field=models.BooleanField(default=False, verbose_name='移動介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='movetransfer',
            field=models.BooleanField(default=False, verbose_name='移乗介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='nyouki',
            field=models.BooleanField(default=False, verbose_name='尿器洗浄'),
        ),
        migrations.AddField(
            model_name='report',
            name='p_toilet',
            field=models.BooleanField(default=False, verbose_name='Pトイレ介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='payment',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='買物'),
        ),
        migrations.AddField(
            model_name='report',
            name='posture',
            field=models.BooleanField(default=False, verbose_name='姿勢の確保'),
        ),
        migrations.AddField(
            model_name='report',
            name='readytocome',
            field=models.BooleanField(default=False, verbose_name='帰宅受入介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='readytomove',
            field=models.BooleanField(default=False, verbose_name='外出準備介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='toilet',
            field=models.BooleanField(default=False, verbose_name='トイレ介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='urination_a',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='排尿量(cc)'),
        ),
        migrations.AddField(
            model_name='report',
            name='urination_t',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='排尿回数'),
        ),
        migrations.AddField(
            model_name='report',
            name='wakeup',
            field=models.BooleanField(default=False, verbose_name='起床介助'),
        ),
        migrations.AddField(
            model_name='report',
            name='wash_dry',
            field=models.BooleanField(default=False, verbose_name='乾燥(物干し)'),
        ),
        migrations.AddField(
            model_name='report',
            name='wash_face',
            field=models.BooleanField(default=False, verbose_name='洗面'),
        ),
        migrations.AddField(
            model_name='report',
            name='wash_hair',
            field=models.BooleanField(default=False, verbose_name='洗髪'),
        ),
        migrations.AddField(
            model_name='report',
            name='wash_inbox',
            field=models.BooleanField(default=False, verbose_name='取り入れ・収納'),
        ),
        migrations.AddField(
            model_name='report',
            name='wash_iron',
            field=models.BooleanField(default=False, verbose_name='アイロン'),
        ),
        migrations.AddField(
            model_name='report',
            name='wash_mouse',
            field=models.BooleanField(default=False, verbose_name='口腔ケア'),
        ),
        migrations.AddField(
            model_name='report',
            name='washing',
            field=models.BooleanField(default=False, verbose_name='寝室'),
        ),
        migrations.AddField(
            model_name='report',
            name='watch_over',
            field=models.BooleanField(default=False, verbose_name='見守り'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hakkan',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '有'), (2, '無')], default=0, verbose_name='発汗'),
        ),
    ]
