# Generated by Django 3.2.6 on 2021-09-20 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0016_auto_20210921_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='schedule',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule'),
        ),
    ]
