# Generated by Django 3.2.6 on 2022-02-10 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0018_alter_report_eating'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='warnings',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='確認事項'),
        ),
        migrations.AlterField(
            model_name='report',
            name='error_code',
            field=models.PositiveSmallIntegerField(choices=[(0, 'なし'), (11, '開始・終了時間不整合'), (12, '実績合計時間が内訳合計時間と不一致'), (13, 'サービス実施時間が最低時間以下'), (14, 'サービス実施時間が15分以上超過'), (90, '開始時間・終了時間が未入力')], default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='エラーコード'),
        ),
    ]
