# Generated by Django 3.2.6 on 2022-02-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0019_auto_20220210_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='error_warn_allowed',
            field=models.BooleanField(default=False, verbose_name='error・warningチェック済み'),
        ),
    ]
