# Generated by Django 3.2.6 on 2022-02-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0020_report_error_warn_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='更新日'),
        ),
    ]
