# Generated by Django 3.2.6 on 2021-09-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0021_rename_makeup_fase_report_makeup_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='face_color',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '---'), (1, '良'), (2, '不良')], default=0, verbose_name='顔色'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hakkan',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '---'), (1, '有'), (2, '無')], default=0, verbose_name='発汗'),
        ),
        migrations.AlterField(
            model_name='report',
            name='linen',
            field=models.BooleanField(default=False, verbose_name='リネン等処理'),
        ),
    ]
