# Generated by Django 3.2.6 on 2021-09-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0021_rename_makeup_fase_report_makeup_face'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='linen',
            field=models.BooleanField(default=False, verbose_name='リネン等処理'),
        ),
    ]
