# Generated by Django 3.2.6 on 2021-09-22 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0022_auto_20210921_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='dring_a',
            new_name='drink_a',
        ),
    ]
