# Generated by Django 3.2.6 on 2022-02-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0022_addrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='nyoukikaijo',
            field=models.BooleanField(default=False, verbose_name='尿器介助'),
        ),
    ]
