# Generated by Django 3.2.6 on 2022-02-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0023_report_nyoukikaijo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='nyoukikaijo',
        ),
        migrations.AddField(
            model_name='report',
            name='makeup_nose',
            field=models.BooleanField(default=False, verbose_name='整容（鼻）'),
        ),
        migrations.AlterField(
            model_name='report',
            name='diapers',
            field=models.BooleanField(default=False, verbose_name='おむつ・パッド交換'),
        ),
        migrations.AlterField(
            model_name='report',
            name='nyouki',
            field=models.BooleanField(default=False, verbose_name='尿器介助・洗浄'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pads',
            field=models.BooleanField(default=False, verbose_name='パッド確認'),
        ),
    ]
