# Generated by Django 3.2.6 on 2021-09-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0022_alter_report_linen'),
        ('schedules', '0023_rename_dring_a_report_drink_a'),
    ]

    operations = [
    ]
