# Generated by Django 3.2.6 on 2021-09-22 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0024_merge_20210922_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='drink_a',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='水分補給'),
        ),
        migrations.AlterField(
            model_name='report',
            name='eat_a',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='食事量'),
        ),
        migrations.AlterField(
            model_name='report',
            name='urination_a',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='排尿量'),
        ),
    ]
