# Generated by Django 3.2.6 on 2022-03-11 04:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0024_auto_20220222_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='urination_a',
            field=models.PositiveSmallIntegerField(choices=[(0, '---'), (1, '少'), (2, '並'), (3, '多')], default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='排尿量'),
        ),
    ]
